module.exports = {
    APPLICATION_READY: 'APPLICATION:READY',
    APPLICATION_UNCAUGHT_EXCEPTION: 'APPLICATION:UNCAUGHT_EXCEPTION',
    APPLICATION_UNHANDLED_REJECTION: 'APPLICATION:UNHANDLED_REJECTION',
    APPLICATION_SHUTDOWN: 'APPLICATION:SHUTDOWN',
    SERVICE_REGISTERED: 'SERVICE:REGISTERED',
    PLUGIN_REGISTERED: 'PLUGIN:REGISTERED'
};